### PR TITLE
fix(filters): replace newline with comma

### LINKED ISSUE #1019: Newlines in input fields causes matching logic to fail
**Version**
1.27.1

**Describe the bug**
Input fields allow newlines, the newlines are added to the matching logic, which results in nothing matching.

**To Reproduce**
```js
{
    "name": "sadsad",
    "version": "1.0",
    "data": {
        "shows": "*Show1*,\n*Show2*"
    }
}
```

```
rejections: (shows not matching. got: Show2 want: *Show1*,\n*Show2*)"}`
```

**Expected behavior**
Newlines should be stripped or replaced by commas I guess?

### PR DESCRIPTION
**Pull request by zze0s**
Replace newline of `shows` with comma.

Fixes #1019

### CODE REVIEW

File: internal/filter/service.go [hunk 1]
```diff
@@ -164,6 +164,10 @@ func (s *service) Update(ctx context.Context, filter *domain.Filter) error {
 		return errors.New("validation: name can't be empty")
 	}
 
+	// replace newline with comma
+	filter.Shows = strings.ReplaceAll(filter.Shows, "\n", ",")
+	filter.Shows = strings.ReplaceAll(filter.Shows, ",,", ",")
```
Comment (KyleSanderson) [inline internal/filter/service.go:169]: https://github.com/KyleSanderson/upgraderr/blob/6db1d724e7672d4da3c28b36287d64b972dddb8b/main.go#L1226
